service: aws-python-simple-http-endpoint-pypy

provider:
  name: aws
  runtime: provided.al2023

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get
