service: aws-python-flask-api-pypy

frameworkVersion: "4"

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: provided.al2023

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
