service: aws-python-rest-api

frameworkVersion: '4'


provider:
  name: aws
  runtime: python3.10
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
